const greeting = guest => `Hello, ${guest}!`;

// describe declares a test suite (a group of tests). Its first argument is a name, the second is a function containing one or more tests.
describe('greeting()', () => { 
    // it() declares a test. Its first argument is a name, the second is a function with the actual test code.
    it('says hello', () => {
        // expect() creates an assertion. It takes a single argument, typically a value generated by the code being tested, and returns an object that exposes a set of matcher functions.
        // toBe() is a matcher that performs a strict equality test between the value being tested (the expect() argument) and the expected value (its own argument).
        expect(greeting('Jest')).toBe('Hello, Jest!');
    });
});